### ISSUE TITLE
Clojure doesn't run

### ISSUE THREAD

**Issue by perimosocordiae** [plasma-umass/doppio#106]
I expect this will be a nontrivial fix, but I want to keep track of our progress. Repro:

    doppio$ make opt
    doppio$ time node console/runner.js --jar ~/Downloads/clojure.jar 
    path.existsSync is now called `fs.existsSync`.
    java.lang.ClassNotFoundException: [Ljava.lang.Object;
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    	at java.security.AccessController.doPrivileged(AccessController.java:190)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    	at java.lang.Class.forName0(Class.java:247)
    	at java.lang.Class.forName(Class.java:247)
    	at clojure.lang.RT.classForName(RT.java:2039)
    	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:977)
    	at clojure.lang.Compiler$HostExpr.tagToClass(Compiler.java:1004)
    	at clojure.lang.Compiler$InvokeExpr.getJavaClass(Compiler.java:3491)
    	at clojure.lang.Compiler$LocalBinding.hasJavaClass(Compiler.java:5493)
    	at clojure.lang.Compiler$LocalBindingExpr.hasJavaClass(Compiler.java:5587)
    	at clojure.lang.Compiler.maybePrimitiveType(Compiler.java:1248)
    	at clojure.lang.Compiler$MethodExpr.emitTypedArgs(Compiler.java:1306)
    	at clojure.lang.Compiler$StaticMethodExpr.emit(Compiler.java:1653)
    	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:5659)
    	at clojure.lang.Compiler$LetExpr.doEmit(Compiler.java:5999)
    	at clojure.lang.Compiler$LetExpr.emit(Compiler.java:5952)
    	at clojure.lang.Compiler$IfExpr.doEmit(Compiler.java:2585)
    	at clojure.lang.Compiler$IfExpr.emit(Compiler.java:2544)
    	at clojure.lang.Compiler$BodyExpr.emit(Compiler.java:5662)
    	at clojure.lang.Compiler$FnMethod.doEmit(Compiler.java:5215)
    	at clojure.lang.Compiler$FnMethod.emit(Compiler.java:5069)
    	at clojure.lang.Compiler$FnExpr.emitMethods(Compiler.java:3600)
    	at clojure.lang.Compiler$ObjExpr.compile(Compiler.java:4233)
    	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3732)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.access$100(Compiler.java:37)
    	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:518)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler.eval(Compiler.java:6515)
    	at clojure.lang.Compiler.load(Compiler.java:6952)
    	at clojure.lang.RT.loadResourceScript(RT.java:359)
    	at clojure.lang.RT.loadResourceScript(RT.java:350)
    	at clojure.lang.RT.load(RT.java:429)
    	at clojure.lang.RT.load(RT.java:400)
    	at clojure.lang.RT.doInit(RT.java:436)
    	at clojure.lang.RT.<clinit>(RT.java:318)
    	at clojure.main.<clinit>(main.java:20)
    Exception in thread "main" java.lang.ClassNotFoundException: [I, compiling:(clojure/core.clj:3539)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6462)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6450)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:936)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6450)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.access$100(Compiler.java:37)
    	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5883)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:5919)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5618)
    	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5054)
    	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3674)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6453)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6443)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.access$100(Compiler.java:37)
    	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:518)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	at clojure.lang.Compiler.analyze(Compiler.java:6262)
    	at clojure.lang.Compiler.analyze(Compiler.java:6223)
    	at clojure.lang.Compiler.eval(Compiler.java:6515)
    	at clojure.lang.Compiler.load(Compiler.java:6952)
    	at clojure.lang.RT.loadResourceScript(RT.java:359)
    	at clojure.lang.RT.loadResourceScript(RT.java:350)
    	at clojure.lang.RT.load(RT.java:429)
    	at clojure.lang.RT.load(RT.java:400)
    	at clojure.lang.RT.doInit(RT.java:436)
    	at clojure.lang.RT.<clinit>(RT.java:318)
    	at clojure.main.<clinit>(main.java:20)
    Caused by: java.lang.ClassNotFoundException: [I
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    	at java.security.AccessController.doPrivileged(AccessController.java:190)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    	at java.lang.Class.forName0(Class.java:247)
    	at java.lang.Class.forName(Class.java:247)
    	at clojure.lang.RT.classForName(RT.java:2039)
    	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:957)
    	at clojure.lang.Compiler$HostExpr.tagToClass(Compiler.java:1004)
    	at clojure.lang.Compiler$LocalBinding.getJavaClass(Compiler.java:5502)
    	at clojure.lang.Compiler$LocalBindingExpr.getJavaClass(Compiler.java:5593)
    	at clojure.lang.Compiler.getMatchingParams(Compiler.java:2324)
    	at clojure.lang.Compiler$StaticMethodExpr.<init>(Compiler.java:1555)
    	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:938)
    	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6455)
    	... 48 more
    
    real	3m16.743s
    user	3m12.412s
    sys 	0m1.379s

I've confirmed that the same error occurs in non-optimized mode, but that takes over an hour to run, so you'll probably want to take my word for it. Looking at the stack trace, it looks like the bug is in our handling of custom classloaders. @int3, any ideas?

**Comment by jvilk** [comment]
This works in `new-objects`!!! Takes *forever* to initialize, though.

```
 ./doppio-fast-dev -jar ~/Downloads/clojure-1.7.0/clojure-1.7.0-slim.jar
Clojure 1.7.0
user=> (def hello (fn [] "Hello world"))
user=> (hello)
"Hello world"
```

Will close upon merging PR #378, and will need to remember to add it to our success list.

**Comment by jvilk** [comment]
Still works. Still takes *forever* to initialize, but it's very fast once that happens.

**Comment by jvilk** [comment]
Actually, the non `-slim` version is much faster at starting up!!
