### ISSUE TITLE
Launch application via sun.misc.Launcher

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#159]
We have implemented our bootstrap classloader in 100% JavaScript, since we assumed that it's a 100% native JVM mechanism.

And, from the spec, that is true; there's no requirement for it to even have a Java object to represent it (methods for getting a class's classloader can return null for the bootstrap classloader).

However, it appears that the HotSpot JVM actually **does** use a Java object for its bootstrap ClassLoader. When it tries to load a class that does not exist, the stack trace looks like this:

```
java.lang.NoClassDefFoundError: classes/test/data/clinit/IDontExist
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at classes.test.CatchingClinitException.main(CatchingClinitException.java:27)
Caused by: java.lang.ClassNotFoundException: classes.test.data.clinit.IDontExist
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 13 more
```

I do not know the exact class of this ClassLoader; maybe it's this `AppClassLoader`:
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/misc/Launcher.java#Launcher.AppClassLoader

In any case, it may be easier for Doppio to adhere to parts of the spec if we used whatever class that HotSpot uses for its bootstrap classloader. It also might remove the need to differentiate between `CustomClassLoader` and `BootstrapClassLoader` in `ClassLoader.coffee`.

One downside to this: It may be more difficult to download interfaces/superclasses in parallel. But that problem will be lessened once we start doing some form of prefetching of class references. :smile:

**Comment by jvilk** [comment]
Small note: We simply need to call the static method `java.lang.ClassLoader.getSystemClassLoader()` at bootup to get this class loader. This method will trigger `Launcher` initialization and such.

**Comment by jvilk** [comment]
We now properly use the AppClassLoader.
