### ISSUE TITLE
Groovy doesn't work

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#213]
It's probably a reflection bug, since the class definitely exists as a file and has the requested method.

```
$ ~/Code/doppio_int3/doppio/doppio -classpath /Users/jvilk/Downloads/groovy-2.1.3/lib/groov -Dscript.name=./groovy -Dprogram.name=groovy -Dgroovy.starter.conf=/Users/jvilk/Downloads/groovy-2.1.3/conf/groovy-starter.conf -Dgroovy.home=/Users/jvilk/Downloads/groovy-2.1.3 -Dtools.jar=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/tools.jar org/codehaus/groovy/tools/GroovyStarter --main groovy.ui.GroovyMain --conf /Users/jvilk/Downloads/groovy-2.1.3/conf/groovy-starter.conf --classpath .
java.lang.NoSuchMethodException: groovy.ui.GroovyMain.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1622)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:97)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)

Exited with code 1
```

**Comment by jvilk** [comment]
Current status for `new-objects` branch:

```
$ ./doppio -classpath /Users/jvilk/Downloads/groovy-2.4.4/lib/groovy-2.4.4.jar -Dscript.name=./groovy -Dprogram.name=groovy -Dgroovy.starter.conf=/Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf -Dgroovy.home=/Users/jvilk/Downloads/groovy-2.4.4 -Dtools.jar=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf /Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf --classpath . /Users/jvilk/Code/doppio_newobjects/doppio/groove.grv
Encountered error: TypeError: undefined is not a function
TypeError: undefined is not a function
    at a.getGenericSignature0()Ljava/lang/String; (eval at <anonymous> (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/jvm.js:1:5139), <anonymous>:1:5759)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:4279)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:9366)
    at a.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:11756)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:6127)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread state dumped to doppio.err.
```

Input file:

```
class HelloWorld {
   def greet( name ){
      "Hello ${name}!"
   }
}

def hm = new HelloWorld()
println hm.greet("Groovy")
```

**Comment by jvilk** [comment]
I fixed that issue. Now Groovy seems to fail in the same manner as Nashorn:

```
$ ./doppio-fast-dev -classpath /Users/jvilk/Downloads/groovy-2.4.4/lib/groovy-2.4.4.jar -Dscript.name=./groovy -Dprogram.name=groovy -Dgroovy.starter.conf=/Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf -Dgroovy.home=/Users/jvilk/Downloads/groovy-2.4.4 -Dtools.jar=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf /Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf --classpath . /Users/jvilk/Code/doppio_newobjects/doppio/groove.grv
Encountered error: Error: Assertion failed: Byte value for method _get is out of bounds: 160

Error: Assertion failed: Byte value for method _get is out of bounds: 160

    at assert (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/assert.js:3:15)
    at validateReturnValue (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:686:13)
    at JVMThread.asyncReturn (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:575:20)
    at Array.Opcodes._return_32 (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/opcodes.js:812:16)
    at BytecodeStackFrame.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:42:28)
    at JVMThread.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:423:45)
    at JVMThread.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:528:22)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:255:32)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread state dumped to doppio.err.
```

**Comment by jvilk** [comment]
Works in 0.3.1.

```
$ doppio -classpath /Users/jvilk/Downloads/groovy-2.4.4/lib/groovy-2.4.4.jar -Dscript.name=./groovy -Dprogram.name=groovy -Dgroovy.starter.conf=/Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf -Dgroovy.home=/Users/jvilk/Downloads/groovy-2.4.4 -Dtools.jar=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf /Users/jvilk/Downloads/groovy-2.4.4/conf/groovy-starter.conf --classpath . /Users/jvilk/Code/doppio_newobjects/doppio/groove.grv
Hello Groovy!
```
