### ISSUE TITLE
can't run Closure Compiler as of 927371e330b3a759b4eb7157df6102fc38df2ff3

### ISSUE THREAD

**Issue by wizzard0** [plasma-umass/doppio#317]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.google.javascript.jscomp.CommandLineRunner$Flags.parse(CommandLineRunner.java:501)
	at com.google.javascript.jscomp.CommandLineRunner$Flags.access$400(CommandLineRunner.java:125)
	at com.google.javascript.jscomp.CommandLineRunner.initConfigFromFlags(CommandLineRunner.java:908)
	at com.google.javascript.jscomp.CommandLineRunner.<init>(CommandLineRunner.java:770)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1204)
Caused by: java.lang.ExceptionInInitializerError
	at java.util.logging.Logger.demandLogger(Logger.java:328)
	at java.util.logging.Logger.getLogger(Logger.java:369)
	at org.kohsuke.args4j.CmdLineParser.<clinit>(CmdLineParser.java:723)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Hook already running
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:60)
	at java.lang.Runtime.addShutdownHook(Runtime.java:212)
	at java.util.logging.LogManager.<init>(LogManager.java:254)
	at java.util.logging.LogManager.<init>(LogManager.java:244)
	at java.util.logging.LogManager$1.run(LogManager.java:192)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:173)
	... 8 more
```

**Comment by jvilk** [comment]
Current status, now that we are Java 8 compatible:

```
$ ./doppio -jar compiler.jar --js hello.js --js_output_file hello-compiled.js
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name org.kohsuke.args4j.Messages, locale en
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.kohsuke.args4j.Messages.format(Messages.java:30)
	at org.kohsuke.args4j.CmdLineParser.parseArgument(CmdLineParser.java:485)
	at com.google.javascript.jscomp.CommandLineRunner$Flags.parse(CommandLineRunner.java:583)
	at com.google.javascript.jscomp.CommandLineRunner$Flags.access$400(CommandLineRunner.java:135)
	at com.google.javascript.jscomp.CommandLineRunner.initConfigFromFlags(CommandLineRunner.java:946)
	at com.google.javascript.jscomp.CommandLineRunner.<init>(CommandLineRunner.java:817)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1365)
Caused by: java.lang.ClassCastException: org.kohsuke.args4j.Messages cannot be cast to ResourceBundle
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2647)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
	... 8 more
```

**Comment by jvilk** [comment]
The above error seems to be an issue with loading resources, which are non-class files relative to classpath items. I think there may be a subtle interplay between our strategy of extracting JAR files prior to running them and the paths on the classpath not matching up to the extraction location.

(Resources can also be classes. The library code tries to load a class with the resource name, then looks for a .properties file with the resource name. The `properties` version should succeed, but it fails, causing the code to report the error for the other type of resource.)

**Comment by jvilk** [comment]
@wizzard0: Closure compiler now works as of the latest commit.
