### ISSUE TITLE
kawa is broken (again)

### ISSUE THREAD

**Issue by perimosocordiae** [plasma-umass/doppio#352]
Something in the latest set of changes to the classloader broke kawa:

```
$ ./doppio-dev -jar kawa-2.0.jar -e '(display 43)'Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at doppio.JarLauncher.main(JarLauncher.java:34)
Caused by: java.lang.NullPointerException: 
	at kawa.Shell.getOutputConsumer(Shell.java:145)
	at kawa.Shell.run(Shell.java:200)
	at kawa.repl.processArgs(repl.java:240)
	at kawa.repl.main(repl.java:871)
	... 5 more
```
(same output with the release-cli version as well).

Looking into the source, the issue seems to be caused by `getDefaultLanguage()` returning null: https://sourceware.org/viewvc/kawa/trunk/gnu/expr/Language.java?view=markup

**Comment by jvilk** [comment]
Fixed by the serialization fix!
