### ISSUE TITLE
Serialization Test Fails

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#356]
```
$ ./doppio classes/test/Serialization
serializing object: s=Hello; i=-7; d=2.7E10
Exception in thread "main" java.lang.NoClassDefFoundError: Cannot load class: classes.test.Serialization$MyClass
	at sun.reflect.GeneratedSerializationConstructorAccessor1.newInstance(unknown)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:967)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1785)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at classes.test.Serialization.main(Serialization.java:24)
```

The AppClassLoader successfully loads and defines the class. We proceed to resolve the class, but there's a context switch to another thread (resolution triggers async file loading). Eventually, something tries to load the class, which fails, causing the error.

The second load should not fail, and should actually cause the thread to:

* Retrieve the defined class if it does not need to be resolved, or
* Attempt to resolve its parent or its parent parent and encounter a classfile load lock.

There are no "resolve locks" in the JVM, though; there are *load* and *initialized* locks.

I've seen this class pass while debugging, which causes a different thread interleaving. Thankfully, it fails most of the time.

**Comment by jvilk** [comment]
OK, so what's going on is:
* `Lsun/misc/Launcher$AppClassLoader;` loads the object successfully. Great.
* Later on, `Lsun/reflect/DelegatingClassLoader;` attempts to load the class by loading it from the bootstrap classloader, which naturally doesn't have it, causing the failure.

I imagine it should delegate to the AppClassLoader, as per the JVM delegation model. Perhaps we're returning the wrong classloader in one of our native methods. Will check.

**Comment by jvilk** [comment]
Our JCL now has a `classLoader` field on `Class` reflection objects that we weren't setting. Fixed.
