### ISSUE TITLE
Nashorn doesn't work

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#358]
Nashorn (found in `java_home/lib/ext/nashorn.jar`; it's the new JavaScript engine) doesn't work. It runs for awhile, and then Doppio exits.

I'm not sure why.

**Comment by jvilk** [comment]
The `new-objects` branch should be able to support Nashorn, but currently the REPL fails during startup.

**DoppioJVM:**

```
$ ./doppio -jar vendor/java_home/lib/ext/nashorn.jar
Encountered error: TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.a.invokevirtual_fast (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/opcodes.js:1:18015)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:2353)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:9315)
    at a.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:11705)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:6076)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread state dumped to doppio.err.
```

**`doppio.err`:**

```
TypeError: undefined is not a function
    at Array.a.invokevirtual_fast (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/opcodes.js:1:18015)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:2353)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:9315)
    at a.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:11705)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:6076)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread 43:
        at jdk.internal.dynalink.DynamicLinker::relink(DynamicLinker.java:245 Bytecode offset: 1)
        at java.lang.invoke.LambdaForm$DMH::invokeSpecial_LLIL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH::reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::invokeExact_MT(LambdaForm$MH)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::invokeObjectGetter(UserAccessorProperty.java:287 Bytecode offset: 15)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::getObjectValue(UserAccessorProperty.java:184 Bytecode offset: 20)
        at jdk.nashorn.internal.runtime.FindProperty::getObjectValue(FindProperty.java:236 Bytecode offset: 12)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2956 Bytecode offset: 91)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2973 Bytecode offset: 40)
        at jdk.nashorn.internal.objects.Global::initFunctionAndObject(Global.java:2950 Bytecode offset: 454)
        at jdk.nashorn.internal.objects.Global::init(Global.java:2516 Bytecode offset: 33)
        at jdk.nashorn.internal.objects.Global::initBuiltinObjects(Global.java:1083 Bytecode offset: 38)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1142 Bytecode offset: 22)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1158 Bytecode offset: 4)
        at jdk.nashorn.internal.runtime.Context::createGlobal(Context.java:1093 Bytecode offset: 5)
        at jdk.nashorn.tools.Shell::run(Shell.java:157 Bytecode offset: 20)
        at jdk.nashorn.tools.Shell::main(Shell.java:136 Bytecode offset: 11)
        at jdk.nashorn.tools.Shell::main(Shell.java:112 Bytecode offset: 10)
        at sun.reflect.NativeMethodAccessorImpl::invoke0(native)
        at sun.reflect.NativeMethodAccessorImpl::invoke(NativeMethodAccessorImpl.java:62 Bytecode offset: 100)
        at sun.reflect.DelegatingMethodAccessorImpl::invoke(DelegatingMethodAccessorImpl.java:43 Bytecode offset: 6)
        at java.lang.reflect.Method::invoke(Method.java:497 Bytecode offset: 56)
        at doppio.JarLauncher::main(JarLauncher.java:34 Bytecode offset: 108)


Thread 84149:
```

**OpenJDK:**

```
$ java -jar vendor/java_home/lib/ext/nashorn.jar
jjs>
```

The error seems to point to a bug in our `invokedynamic`/signature polymorphic function support. Certainly attempting to invoke an `undefined` object is a big red flag!

**Comment by jvilk** [comment]
Current status after fixing some bugs and getting further:

```
$ ./doppio-fast-dev -jar vendor/java_home/lib/ext/nashorn.jar
Encountered error: Error: Assertion failed: Invalid double value: [object Object]

Error: Assertion failed: Invalid double value: [object Object]

    at assert (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/assert.js:3:15)
    at validateReturnValue (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:711:17)
    at JVMThread.asyncReturn (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:575:20)
    at Array.Opcodes._return_64 (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/opcodes.js:821:16)
    at BytecodeStackFrame.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:42:28)
    at JVMThread.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:423:45)
    at JVMThread.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:528:22)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/fast-dev-cli/src/threading.js:255:32)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread state dumped to doppio.err.
```

doppio.err:

```
Thread 43:
        at jdk.nashorn.internal.objects.NativeNumber::lookupPrimitive(NativeNumber.java:323 Bytecode offset: 11)
        at jdk.nashorn.internal.objects.Global::primitiveLookup(Global.java:1127 Bytecode offset: 22)
        at jdk.nashorn.internal.runtime.linker.NashornPrimitiveLinker::getGuardedInvocation(NashornPrimitiveLinker.java:71 Bytecode offset: 29)
        at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker::getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176 Bytecode offset: 60)
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker::getGuardedInvocation(CompositeGuardingDynamicLinker.java:124 Bytecode offset: 29)
        at jdk.internal.dynalink.support.LinkerServicesImpl::getGuardedInvocation(LinkerServicesImpl.java:154 Bytecode offset: 23)
        at jdk.internal.dynalink.DynamicLinker::relink(DynamicLinker.java:253 Bytecode offset: 92)
        at java.lang.invoke.LambdaForm$DMH::invokeSpecial_LLIL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH::reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::invokeExact_MT(LambdaForm$MH)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::invokeObjectGetter(UserAccessorProperty.java:287 Bytecode offset: 15)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::getObjectValue(UserAccessorProperty.java:184 Bytecode offset: 20)
        at jdk.nashorn.internal.runtime.FindProperty::getObjectValue(FindProperty.java:236 Bytecode offset: 12)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2956 Bytecode offset: 91)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2973 Bytecode offset: 40)
        at jdk.nashorn.internal.objects.Global::initFunctionAndObject(Global.java:2950 Bytecode offset: 454)
        at jdk.nashorn.internal.objects.Global::init(Global.java:2516 Bytecode offset: 33)
        at jdk.nashorn.internal.objects.Global::initBuiltinObjects(Global.java:1083 Bytecode offset: 38)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1142 Bytecode offset: 22)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1158 Bytecode offset: 4)
        at jdk.nashorn.internal.runtime.Context::createGlobal(Context.java:1093 Bytecode offset: 5)
        at jdk.nashorn.tools.Shell::run(Shell.java:157 Bytecode offset: 20)
        at jdk.nashorn.tools.Shell::main(Shell.java:136 Bytecode offset: 11)
        at jdk.nashorn.tools.Shell::main(Shell.java:112 Bytecode offset: 10)
        at sun.reflect.NativeMethodAccessorImpl::invoke0(native)
        at sun.reflect.NativeMethodAccessorImpl::invoke(NativeMethodAccessorImpl.java:62 Bytecode offset: 100)
        at sun.reflect.DelegatingMethodAccessorImpl::invoke(DelegatingMethodAccessorImpl.java:43 Bytecode offset: 6)
        at java.lang.reflect.Method::invoke(Method.java:497 Bytecode offset: 56)
        at doppio.JarLauncher::main(JarLauncher.java:34 Bytecode offset: 108)

```

**Comment by jvilk** [comment]
I was wrong: It's unboxing code for the `Integer` class (`java.lang.Integer.doubleValue()`).

**Comment by jvilk** [comment]
Current status after fixing an autoboxing issue:

```
$ ./doppio-fast-dev -jar vendor/java_home/lib/ext/nashorn.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at doppio.JarLauncher.main(JarLauncher.java:34)
Caused by: ECMAScript Exception: [object Error]
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:103)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:71)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.runtime.UserAccessorProperty.invokeObjectGetter(UserAccessorProperty.java:287)
	at jdk.nashorn.internal.runtime.UserAccessorProperty.getObjectValue(UserAccessorProperty.java:184)
	at jdk.nashorn.internal.runtime.FindProperty.getObjectValue(FindProperty.java:236)
	at jdk.nashorn.internal.runtime.ScriptObject.get(ScriptObject.java:2956)
	at jdk.nashorn.internal.runtime.ScriptObject.get(ScriptObject.java:2973)
	at jdk.nashorn.internal.objects.Global.initFunctionAndObject(Global.java:2950)
	at jdk.nashorn.internal.objects.Global.init(Global.java:2516)
	at jdk.nashorn.internal.objects.Global.initBuiltinObjects(Global.java:1083)
	at jdk.nashorn.internal.runtime.Context.initGlobal(Context.java:1142)
	at jdk.nashorn.internal.runtime.Context.initGlobal(Context.java:1158)
	at jdk.nashorn.internal.runtime.Context.createGlobal(Context.java:1093)
	at jdk.nashorn.tools.Shell.run(Shell.java:157)
	at jdk.nashorn.tools.Shell.main(Shell.java:136)
	at jdk.nashorn.tools.Shell.main(Shell.java:112)
	... 5 more
```

**Comment by jvilk** [comment]
I've fixed some serious invokedynamic bugs, and now we're in familiar territory:

```
 ./doppio-fast-dev -ea -jar vendor/java_home/lib/ext/nashorn.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at doppio.JarLauncher.main(JarLauncher.java:34)
Caused by: java.lang.UnsatisfiedLinkError: Native method 'sun.misc.Unsafe.fullFence()V' not implemented.
Please fix or file a bug at https://github.com/plasma-umass/doppio/issues
	at sun.misc.Unsafe.fullFence(Native Method)
	at java.lang.invoke.MethodHandle.updateForm(MethodHandle.java:1434)
	at java.lang.invoke.MethodHandle.customize(MethodHandle.java:1442)
	at java.lang.invoke.Invokers.maybeCustomize(Invokers.java:407)
	at java.lang.invoke.Invokers.checkCustomized(Invokers.java:398)
	at jdk.nashorn.internal.runtime.AccessorProperty.invokeSetter(AccessorProperty.java:488)
	at jdk.nashorn.internal.runtime.AccessorProperty.setValue(AccessorProperty.java:517)
	at jdk.nashorn.internal.runtime.ScriptObject.erasePropertyValue(ScriptObject.java:906)
	at jdk.nashorn.internal.runtime.ScriptObject.deleteOwnProperty(ScriptObject.java:918)
	at jdk.nashorn.internal.objects.ScriptFunctionImpl.makeFunction(ScriptFunctionImpl.java:205)
	at jdk.nashorn.internal.objects.ScriptFunctionImpl.makeFunction(ScriptFunctionImpl.java:219)
	at jdk.nashorn.internal.objects.ScriptFunctionImpl.makeFunction(ScriptFunctionImpl.java:241)
	at jdk.nashorn.internal.objects.Global.initErrorObjects(Global.java:2642)
	at jdk.nashorn.internal.objects.Global.init(Global.java:2569)
	at jdk.nashorn.internal.objects.Global.initBuiltinObjects(Global.java:1083)
	at jdk.nashorn.internal.runtime.Context.initGlobal(Context.java:1142)
	at jdk.nashorn.internal.runtime.Context.initGlobal(Context.java:1158)
	at jdk.nashorn.internal.runtime.Context.createGlobal(Context.java:1093)
	at jdk.nashorn.tools.Shell.run(Shell.java:157)
	at jdk.nashorn.tools.Shell.main(Shell.java:136)
	at jdk.nashorn.tools.Shell.main(Shell.java:112)
	... 5 more
```

**Comment by jvilk** [comment]
TIL `jdk/nashorn/internal/scripts/Script$\^shell\_` is a [valid class name](http://mail.openjdk.java.net/pipermail/nashorn-dev/2014-October/003674.html), which messes with how we define constructors. The fix is simple, but [it's interesting how liberal Java is](https://blogs.oracle.com/jrose/entry/symbolic_freedom_in_the_vm).

**Comment by jvilk** [comment]
Oh jeez, it looks like I need to unescape the escape characters internally, since the method names are not escaped?

`Couldn't find method Ljdk/nashorn/internal/scripts/Script$^shell_; :createProgramFunction(Ljdk/nashorn/internal/runtime/ScriptObject;)Ljdk/nashorn/internal/runtime/ScriptFunction; in Ljdk/nashorn/internal/scripts/Script$\^shell\_;.`

(and, yes, it appears that that function begins with the `:` character)

**Comment by jvilk** [comment]
I have to fix every place where we `eval` JVM symbols to re-escape JVM names, since they may contain `\` escape characters that JavaScript will remove from string literals (e.g. `"jdk/nashorn/internal/scripts/Script$\^shell\_` => `"jdk/nashorn/internal/scripts/Script$^shell_"`).

**Comment by jvilk** [comment]
(In good news, I do make it to a REPL before things blow up. :smile:  )

**Comment by jvilk** [comment]
Whoops. Opening until `new-objects` is merged. Forgot about that convention.

**Comment by jimfb** [comment]
Wow, Nashorn works now?  That's fancy magic.  Great work @jvilk!

**Comment by jvilk** [comment]
@jimfb Sure does! Here's me playing around with the latest master branch:

```
$ ./doppio-fast-dev -ea -jar vendor/java_home/lib/ext/nashorn.jar
jjs> 1+1
2
jjs> (function() { [1,2,3].forEach(print); })()
1 0 1,2,3
2 1 1,2,3
3 2 1,2,3
jjs> (function() { [1,2,3].forEach(function(n) { print(n); })()
ECMAScript Exception: SyntaxError: <shell>:1:58 Expected } but found eof
(function() { [1,2,3].forEach(function(n) { print(n); })()
                                                          ^
jjs> (function() { [1,2,3].forEach(function(n) { print(n); }); })()
1
2
3
jjs>
```

It takes a little while to boot up.

**Comment by jvilk** [comment]
(For that second example, I forgot that JavaScript's `forEach` actually includes the index and array as secondary arguments. That output is "Working As Expected".)

**Comment by jvilk** [comment]
Also, I should check if I broke it... but Scala and a bunch of other languages work now, too.
