### ISSUE TITLE
Support Nashorn

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#377]
The `new-objects` branch should be able to support Nashorn, but currently the REPL fails during startup.

**DoppioJVM:**

```
$ ./doppio -jar vendor/java_home/lib/ext/nashorn.jar
Encountered error: TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.a.invokevirtual_fast (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/opcodes.js:1:18015)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:2353)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:9315)
    at a.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:11705)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:6076)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread state dumped to doppio.err.
```

**`doppio.err`:**

```
TypeError: undefined is not a function
    at Array.a.invokevirtual_fast (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/opcodes.js:1:18015)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:2353)
    at a.run (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:9315)
    at a.setStatus (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:11705)
    at Immediate._onImmediate (/Users/jvilk/Code/doppio_newobjects/doppio/build/release-cli/src/threading.js:1:6076)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Thread 43:
        at jdk.internal.dynalink.DynamicLinker::relink(DynamicLinker.java:245 Bytecode offset: 1)
        at java.lang.invoke.LambdaForm$DMH::invokeSpecial_LLIL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH::reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::exactInvoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH::invokeExact_MT(LambdaForm$MH)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::invokeObjectGetter(UserAccessorProperty.java:287 Bytecode offset: 15)
        at jdk.nashorn.internal.runtime.UserAccessorProperty::getObjectValue(UserAccessorProperty.java:184 Bytecode offset: 20)
        at jdk.nashorn.internal.runtime.FindProperty::getObjectValue(FindProperty.java:236 Bytecode offset: 12)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2956 Bytecode offset: 91)
        at jdk.nashorn.internal.runtime.ScriptObject::get(ScriptObject.java:2973 Bytecode offset: 40)
        at jdk.nashorn.internal.objects.Global::initFunctionAndObject(Global.java:2950 Bytecode offset: 454)
        at jdk.nashorn.internal.objects.Global::init(Global.java:2516 Bytecode offset: 33)
        at jdk.nashorn.internal.objects.Global::initBuiltinObjects(Global.java:1083 Bytecode offset: 38)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1142 Bytecode offset: 22)
        at jdk.nashorn.internal.runtime.Context::initGlobal(Context.java:1158 Bytecode offset: 4)
        at jdk.nashorn.internal.runtime.Context::createGlobal(Context.java:1093 Bytecode offset: 5)
        at jdk.nashorn.tools.Shell::run(Shell.java:157 Bytecode offset: 20)
        at jdk.nashorn.tools.Shell::main(Shell.java:136 Bytecode offset: 11)
        at jdk.nashorn.tools.Shell::main(Shell.java:112 Bytecode offset: 10)
        at sun.reflect.NativeMethodAccessorImpl::invoke0(native)
        at sun.reflect.NativeMethodAccessorImpl::invoke(NativeMethodAccessorImpl.java:62 Bytecode offset: 100)
        at sun.reflect.DelegatingMethodAccessorImpl::invoke(DelegatingMethodAccessorImpl.java:43 Bytecode offset: 6)
        at java.lang.reflect.Method::invoke(Method.java:497 Bytecode offset: 56)
        at doppio.JarLauncher::main(JarLauncher.java:34 Bytecode offset: 108)


Thread 84149:
```

**OpenJDK:**

```
$ java -jar vendor/java_home/lib/ext/nashorn.jar
jjs>
```

The error seems to point to a bug in our `invokedynamic`/signature polymorphic function support. Certainly attempting to invoke an `undefined` object is a big red flag!

**Comment by jvilk** [comment]
Dupe of #358.
