### ISSUE TITLE
getCanonicalHostName() throws NullPointerException 

### ISSUE THREAD

**Issue by cool2man** [plasma-umass/doppio#487]
InetAddress.getLocalHost().getCanonicalHostName() throws a NullPointerException.
Stack trace:
```
at java.net.InetAddress.getCachedAddresses(InetAddress.java:897)
at java.net.InetAddress.getAllByName0(InetAddress.java:1272)
at java.net.InetAddress.getAllByName0(InetAddress.java:1253)
at java.net.InetAddress.getHostFromNameService(InetAddress.java:634)
at java.net.InetAddress.getCanonicalHostName(InetAddress.java:588)
```

**Comment by nybbs2003** [comment]
I suggest to return "doppio" instead.
