### ISSUE TITLE
Equinox OSGi container error

### ISSUE THREAD

**Issue by zzj1213** [plasma-umass/doppio#488]
/home $ java -jar org.eclipse.osgi_3.11.1.jar -console                          
Exception in thread "main" java.lang.ClassNotFoundException: Cannot load class: 
org.eclipse.core.runtime.adaptor.EclipseStarter                                 
        at java.lang.Class.forName0(Native Method)                              
        at java.lang.Class.forName(Class.java:348)                              
        at doppio.JarLauncher.main(JarLauncher.java:32)

**Comment by jvilk** [comment]
I get the following error with the Node frontend:

```
$ ./doppio -jar ~/Downloads/org.eclipse.osgi_3.11.1.v20160708-1632.jar -console
java.lang.ExceptionInInitializerError
	at org.eclipse.osgi.internal.framework.EquinoxConfiguration.initializeProperties(EquinoxConfiguration.java:1029)
	at org.eclipse.osgi.internal.framework.EquinoxConfiguration.<init>(EquinoxConfiguration.java:497)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:62)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:31)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:303)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:239)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.main(EclipseStarter.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at doppio.JarLauncher.main(JarLauncher.java:34)
Caused by: java.security.ProviderException: engineSetSeed() failed.
	at doppio.security.NodePRNG.engineSetSeed(Native Method)
	at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:209)
	at java.security.SecureRandom.<init>(SecureRandom.java:190)
	at org.eclipse.osgi.internal.framework.UniversalUniqueIdentifier.computeNodeAddress(UniversalUniqueIdentifier.java:127)
	at org.eclipse.osgi.internal.framework.UniversalUniqueIdentifier.<clinit>(UniversalUniqueIdentifier.java:35)
```

That error is caused by Node's secure PRNG not accepting a seed. We might have to build a secure PRNG on top of Node's secure PRNG that can accept a seed.
