### ISSUE TITLE
Encountered error: TypeError: Cannot read property 'getLoader' of undefined

### ISSUE THREAD

**Issue by hhuynh** [plasma-umass/doppio#500]
Failed to run provided example

% ../../doppio -cp example example.App

Encountered error: TypeError: Cannot read property 'getLoader' of undefined
TypeError: Cannot read property 'getLoader' of undefined
    at a.getLoader (/Volumes/Unix/workspace/doppio/src/threading.ts:709:49)
    at a.throwNewException (/Volumes/Unix/workspace/doppio/src/threading.ts:1159:44)
    at b.a.throwClassNotFoundException (/Volumes/Unix/workspace/doppio/src/ClassLoader.ts:341:12)
    at a.cb (/Volumes/Unix/workspace/doppio/src/ClassLoader.ts:554:14)
    at a.run (/Volumes/Unix/workspace/doppio/src/threading.ts:552:12)
    at a.run (/Volumes/Unix/workspace/doppio/src/threading.ts:851:12)
    at Immediate.<anonymous> (/Volumes/Unix/workspace/doppio/src/threadpool.ts:84:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by ttjordan** [comment]
I have the same issue

**Comment by jvilk** [comment]
I've confirmed and reproduced the issue! I'll take a look when I have time. Thanks for reporting.

**Comment by jvilk** [comment]
Oof, this is an unfortunate non-error message.

You're actually specifying your classpath incorrectly! If you try:

```
java -cp docs/examples/example example.App
```

...notice that it doesn't work. Instead, you need to do:

```
java -cp docs/examples example.App
```

Thus, run the following command instead:

```
../../doppio -cp docs/examples example.App
```

With that said, this should really give you a better error message!

**Comment by ttjordan** [comment]
Thank you a lot for a quick reply! It worked!

**Comment by hhuynh** [comment]
yes that was it. Though if you're inside the docs/examples folder, the correct command is:

 %> ../../doppio -cp . example.App
