### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Solant** [plasma-umass/doppio#503]
Tried to build the project but got this error on current master (b6dbd73).
```
Using tsc v2.4.2
console/download_jdk.ts(51,13): error TS2559: Type 'string' has no properties in common with type 'RequestOptions'.
console/download_jdk.ts(51,19): error TS7006: Parameter 'res' implicitly has an 'any' type.
node_modules/@types/bluebird/index.d.ts(623,33): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(623,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(810,39): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(810,78): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(813,27): error TS2304: Cannot find name 'Map'.
node_modules/@types/bluebird/index.d.ts(813,65): error TS2304: Cannot find name 'Map'.
src/natives/sun_nio.ts(710,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((path: string | Buffer, callback?: (err: ErrnoException, stats: Stats) => any) => void) | { (pat...' has no compatible call signatures.
src/natives/sun_nio.ts(710,28): error TS7006: Parameter 'err' implicitly has an 'any' type.
src/natives/sun_nio.ts(710,33): error TS7006: Parameter 'stat' implicitly has an 'any' type.

>> 11 non-emit-preventing type warnings  
>> Error: tsc return code: 2
Warning: Task "ts:dev-cli" failed. Use --force to continue.

Aborted due to warnings.
/home/solant/Documents/doppio/prepublish.js:13
    throw new Error("Program exited with code " + code);
    ^

Error: Program exited with code 3
    at checkCode (/home/solant/Documents/doppio/prepublish.js:13:11)
    at ChildProcess.<anonymous> (/home/solant/Documents/doppio/prepublish.js:27:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doppiojvm@0.5.0 prepublish: `node ./prepublish.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doppiojvm@0.5.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jvilk** [comment]
It looks like it's using too new of a version of TypeScript. Could you try installing the dependencies with `yarn install` instead? That should give you the exact version of the dependencies used during the last successful build.

**Comment by Solant** [comment]
That's embarrassing, looks like I need to learn how to read manuals. Now build works fine. Thanks a lot.
