### ISSUE TITLE
3 Issues - Fib example and my own JAR apps

### ISSUE THREAD

**Issue by MooseValley** [plasma-umass/doppio#504]
1).  Uploaded a simple GUI game:

/home $ java -jar Oblotteration.jar
Exception in thread "main" java.lang.ClassNotFoundException: LOblotteration ;
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at doppio.JarLauncher.main(JarLauncher.java:32)

Not sure whats wrong, Oblotteration.jar runs perfectly on Linux, Windows, and Mac OS.
Nothing in my code uses / references "LOblotteration", so don't understand this error message.

2). Also tried to run the Fib example suggested:

/home $ javac classes/demo/Fib.java
Please be patient; this command may need to download resources from the network.
classes/demo/Fib.java:4: error: cannot access String
  public static void main(String[] args) {
                          ^
  bad class file: /home/vendor/java_home/lib/rt.jar(java/lang/String.class)
    unable to access file: Error: EIO: null
    Please remove or make sure it appears in the correct subdirectory of the cla
sspath.
Compiler failed.

3).  Uploaded a a ProGuarded Lottery Number Selector GUI app and it did nothing - no errors, nothing.
java -jar LotteryNumberSelector_proguard.jar
and it just returned to the command line - no GUI, no errors, nothing.

What are the limitations on the JARs I can upload / run in a browser ?
Can they use / include other JARs ?  e.g. can I upload apps that connect to SQL Server (requires an extra jar: sqljdbc42.jar) ?

Keep up the great work.  Very exciting project !

Moose

**Comment by stefan-reich** [comment]
DoppioJVM doesn't support GUIs. You mean AWT/Swing, right? Yeah, that's not working.

> 2). Also tried to run the Fib example suggested

On their demo page? Works fine for me.

PS: I know the question is literally 4 years old... so what :D
